### ISSUE TITLE
Entity Switches are now invisible when off. 

### ISSUE THREAD

**Issue by HutchMD** [home-assistant-community-themes/amoled#15]
I love this theme!

However, The new Home Assistant update (106.5) changed how this theme works.
The knobs for the switches for any entity is now completely black and blends in with the background.
The switches are only visible if they are switched on.

Which value would I have to edit in the theme file to make entity switches visible again?

**Comment by CodeFinder2** [comment]
Can confirm this problem 🤔

**Comment by lance36** [comment]
I will update My instance and take a look in the following days, if you
figure it out meanwhile feel free to submit a pr :)

Il dom 8 mar 2020, 14:21 Adrian Böckenkamp <notifications@github.com> ha
scritto:

**Comment by vandalon** [comment]
adding the following 2 lines fixes this:

```
  switch-unchecked-button-color: "#212121"
  switch-unchecked-track-color: "#212121"
```

**Comment by CodeFinder2** [comment]
@vandalon What about making a Pull Request? ;-)
