### ISSUE TITLE
MFA / 2FA QR code not visible

### ISSUE THREAD

**Issue by lowfat32** [home-assistant-community-themes/amoled#23]
Since the background is black the QR code isn't visible. I changed paper-dialog-background-color: "#525252" to give it visibility. However it changes all the backgrounds for entity cards, which also have a grey text. I tried changing every other color in the yaml file. But nothing seemed to change it.

Same issue for another of your themes, the amoled-blue. However in that case paper-dialog-background-color has to be added.

**Comment by lance36** [comment]
Sorry I never used QR codes, and obviously never encountered the issue
If I may say tho, is the QR code image that should have a White background and not relay on the background of the frontend?
I believe this needs to be fixed upstream
