### ISSUE TITLE
missing configuration for "/lovelace/hass-unused-entities"

### ISSUE THREAD

**Issue by palhaland** [home-assistant-community-themes/amoled#7]
When viewing the page "lovelace/hass-unused-entities" the entity filter is all white in this theme.

**Comment by indykoning** [comment]
Adding
```
  # fix for device configuration screen
  card-background-color: "var(--paper-card-background-color)"
```
at the end of the theme file should fix this.
I don't have time right now to create a PR for it.

**Comment by maartenpaauw** [comment]
I can create a PR this weekend 😄

**Comment by maartenpaauw** [comment]
I've created a branch with this fix. Feel free to test it out 😄

**Comment by lance36** [comment]
Merged :)
Thanks!
